### ISSUE TITLE
Road Legal Electric Bike/Scooter

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#14]
In the process of _considering_ moving house to closer to Palmers Road to reduce commuting (_time_): https://github.com/dwyl/phase-two/issues/11 I got thinking ... 

> Hold on, **what _problem_** are we **trying to _solve_**? 

At present our commute is **35 minutes** (_each way_) by _bike_ and **_80 minutes_** (_each way_) catching _**two busses**_ ... this is "_getting old_"; especially considering the value of our time!

is there "MVP" for this?

> **Should we _consider_ electric bicycles**? (_which will reduce commute time without impacting the environment_)

_Criteria_ for an electric scooter? 

http://www.evoscooters.co.uk/road-legal-scooters/800w-citi-road-legal-evo-powerboard-electric-scooter-lithium-lifepo4-battery-es08eec-lithium.html £930 at the time of researching/writing:

![evo-powerboards-citi-road-legal-electric-scooter](https://cloud.githubusercontent.com/assets/194400/19624802/40a03e34-98fe-11e6-98c9-99be37e06dc9.png)

It's also available on Amazon: https://www.amazon.co.uk/EVO-Powerboard-electric-scooter-Lithium/dp/B00SH9SF5S/ but is _more expensive_ than buying it directly from [EvoScooters.co.uk](http://www.evoscooters.co.uk/road-legal-scooters/800w-citi-road-legal-evo-powerboard-electric-scooter-lithium-lifepo4-battery-es08eec-lithium.html)

![evo-powerboards-citi-road-legal-electric-scooter-amazon-price-979 25](https://cloud.githubusercontent.com/assets/194400/19624759/296e0c24-98fd-11e6-90b2-56d80f02cb96.png)
### Considerations:
- Small wheels on the mini scooter mean potholes will be felt.
- Might need to get a motorcycle license ... (_further investigation required_)
- Might not be _that_ much faster than cycling.

Note: there appears to be a _more powerful_ version: http://www.evoscooters.co.uk/electric-folding-scooters/es17-1600w-48v-lithium-lifepo4-battery-black.html but it's _unclear_ if its road legal.

**Comment by markwilliamfirth** [comment]
If you ever want some electric bike recommendations let me know because I've done a fair bit of research on this :)

**Comment by nelsonic** [comment]
@markwilliamfirth solid. (_why does that `not` surprise me..._?) 😉

**Comment by iteles** [comment]
Soooooo... seeing as #11 , can we close this issue? :blush:

**Comment by nelsonic** [comment]
@iteles not _really_ it might not be applicable to _us_ anymore (_given that we have killed the commute-cockroach with a sledgehammer_) but there's someone `else` who _might_ still be interested in an Electric Bike for getting from Whitecross Market to Palmers Road ... 😉 

> relates to: https://github.com/dwyl/start-here/issues/108

**Comment by markwilliamfirth** [comment]
hah - I'm not looking for one right now so I think we can close it. [Here](https://docs.google.com/spreadsheets/d/1tYD1irgKtQik7-QfIdEWZTe_Zli6gmXQBmXOdxiCfFI/edit?usp=sharing) is my *outdated* spreadsheet though in case anyone is interested (haven't completed it or researched everything that's out there).

Most interesting one I've seen is [Vello](https://www.indiegogo.com/projects/vello-bike-the-first-self-charging-folding-e-bike-bicycle#/). The self-charging feature is really cool.

**Comment by nelsonic** [comment]
@markwilliamfirth the Vello bike is _incredible_!! 😮  
I'll need to save up the pennies to afford one ... 💰 🚲 
but it's just jumped to the *top* of my list! 📝 
great spreadsheet! 😍 
OK cool. happy to close the issue if no longer required. 👍
