### ISSUE TITLE
Youtube Link Dead

### ISSUE THREAD

**Issue by raptortech-js** [dwyl/phase-two#19]
It looks like the "Before the Flood" documentary was removed from Youtube, and is now only available for pay, so the link on the README now points to a page that says "this video is private." This might be a better link: https://www.youtube.com/watch?v=ohwU3Sfdckc

**Comment by nelsonic** [comment]
That's super annoying!
A bit of searching and I found: https://www.youtube.com/watch?v=codqzJ4onGc
[![before-the-flood-video](https://cloud.githubusercontent.com/assets/194400/20142470/c17817ca-a68c-11e6-9c2b-b8833b839a7d.png)](https://www.youtube.com/watch?v=codqzJ4onGc) 
Still _free_ on **NatGeo TVUK** on YouTube _for now_ ...
We should probably _download_ it in case it gets taken down again...?

**Comment by raptortech-js** [comment]
It's available to torrent through PirateBay, so you can get a high-quality version: https://thepiratebay.org/torrent/16159258/Before.the.Flood.2016.HDTV.x264-CROOKS[ettv]

**Comment by nelsonic** [comment]
@raptortech-js what's a "_torrent_"...?

**Comment by raptortech-js** [comment]
The [BitTorrent](https://en.wikipedia.org/wiki/BitTorrent) protocol is a highly efficient, highly distributed peer-to-peer file sharing protocol, commonly used for sharing copyrighted material without permission.

**Comment by raptortech-js** [comment]
Thanks, for that Youtube link, by the way. It even has subtitles, which have been super hard to find elsewhere.

**Comment by nelsonic** [comment]
If anyone reading this has **Netflix**, the Doc is available in _most_ countries.
