### ISSUE TITLE
"Drones"

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#24]
Whether we _like_ it or _not_ drones are going to be taking over our skies in the _near_ future. 

> http://www.recode.net/2016/11/10/13553070/drone-startup-zipline-health-care-delivery-rwanda
> http://www.businessinsider.com/zipline-raises-25-million-for-humanitarian-drone-deliveries-2016-11

I'm _obviously_ keen on learning how to fly drones for arial photography. https://github.com/dwyl/summer/issues/4
But I _also_ see the _many_ opportunities for _practical_ applications ... 
http://news.nationalgeographic.com/news/2013/12/131202-drone-uav-uas-amazon-octocopter-bezos-science-aircraft-unmanned-robot/ see `#4` on the list...

I'm _resisting_ the temptation to "_waste_" money on the DJI Mavic Pro: https://youtu.be/p1d_ptE6yrc
Even though every _neuron_ of my child-like-mind is trying to _convince_ me it's a _great_ idea and I "_need_" one!!

http://www.maplin.co.uk/p/dji-mavic-pro-4k-quadcopter-drone-fly-more-combo-n88em
![maplin-dji-mavic-pro](https://cloud.githubusercontent.com/assets/194400/20232269/e904f65e-a85e-11e6-8638-13227650942f.png)

When the time comes we will get one for viewing our land and the surrounding area.

**Comment by nelsonic** [comment]
Wow. https://www.youtube.com/watch?v=XBHuftMcmis 😮 
![dji-inspire-2](https://cloud.githubusercontent.com/assets/194400/20341710/3b7dd9c2-abdf-11e6-8c91-ccbd11788a4c.png)

**Comment by sohilpandya** [comment]
Ummmm. lets do it!!!! 😆 😆 😆

**Comment by nelsonic** [comment]
Sadly, the price of the `Inspire 2` is a _little_ bit silly: http://store.dji.com/product/inspire-2
![screen shot 2016-11-16 at 14 10 51](https://cloud.githubusercontent.com/assets/194400/20350427/c6ec42ce-ac06-11e6-9371-c6e302dedbb9.png)

It's not a "_consumer_" device...

**Comment by sohilpandya** [comment]
JESUS!

**Comment by nelsonic** [comment]
@sohilpandya I'm on the "tell me about Mavic Pro availability" list for Maplin:
![image](https://cloud.githubusercontent.com/assets/194400/22508304/483adc80-e881-11e6-9c24-2731a3307c1a.png)
But if you think we should _consider_ buying it _directly_ from DJI: https://store.dji.com/product/mavic-pro please update. 👍 
(_our main objective is having a **good customer service** if anything goes "wrong" with it..._!)

**Comment by sohilpandya** [comment]
@nelsonic DJI is probably not the best place to buy the drone from:
<img width="974" alt="screen shot 2017-02-01 at 15 09 30" src="https://cloud.githubusercontent.com/assets/2305591/22512555/4d86cb30-e891-11e6-96f8-fd32e27222a5.png">


**7 Day returns policy is not great.. 😢**

IMO Maplins is the best bet for getting this due to its great customer service.

**Comment by nelsonic** [comment]
@sohilpandya agreed. 👍

**Comment by sohilpandya** [comment]
I am **super** excited about this! 🎉 🎉 
- In terms of practice, I'm not sure about it, I've personally had experience flying DJI drones and they are super easy to fly. For starters, it might be best to take it out in a completely open area (Vic park) 

Some accessories which may come in handy: 
- [longer legs](https://www.amazon.com/SKYREAT-Mavic-Landing-Gear-Stabilizers/dp/B01N99MMT8/ref=pd_lpo_421_tr_t_3?_encoding=UTF8&psc=1&refRID=94VJBCVE8NYPSJJ4GWY0)
- [More Propellers](https://www.amazon.com/SKYREAT-Mavic-Landing-Gear-Stabilizers/dp/B01N99MMT8/ref=pd_lpo_421_tr_t_3?_encoding=UTF8&psc=1&refRID=94VJBCVE8NYPSJJ4GWY0)
- We should get a lens cover which will cover the camera when it's not in use. 
- [Bag](http://store.dji.com/product/mavic-shoulder-bag#/?_k=wq9pa7) **Although I recommend that we look for alternatives that are cheaper** (will post if I find a good one here!) 👍

**Comment by sohilpandya** [comment]
I have just spent the last hour watching other people fly/talk about the drone... 😟 

https://youtu.be/mBaPcpddMZ8?t=3m40s
https://www.youtube.com/watch?v=WsHpdQPIMvI

**Comment by nelsonic** [comment]
@sohilpandya thanks for doing the research!! (_and sharing the links!_)
I ordered this hard case (_because it looked good..._)
https://www.amazon.co.uk/gp/product/B01N20K9ES/
![image](https://cloud.githubusercontent.com/assets/194400/22621381/4f681b1c-eb1a-11e6-97d9-1a00659b6fed.png)

**Comment by sohilpandya** [comment]
@nelsonic 🎉 Ah, didn't know we had ordered an extra one. It gives us a total of ~30-45min+ of flight time with 2 batteries so plenty imo 👍

**Comment by nelsonic** [comment]
![maplin order](https://cloud.githubusercontent.com/assets/194400/22766325/abc84a12-ee6c-11e6-9a14-52c15a580add.png)
@sohilpandya looks like we be flyin' this weekend! 🛩  (_not quite "G6" but, moar **fun-per-dollar**!_)
wanna Meet Me @Maplin at Midday? 🕛  ❓ 

P.S: have you seen: http://dronelife.com/2016/05/07/5-apps-every-drone-pilot-consider/ ?
especially "Lichi": https://flylitchi.com ... see: https://youtu.be/ZvdWSGrf_Ak
FPV: https://youtu.be/ewznIo8RTlg ...? 😮

**Comment by sohilpandya** [comment]
@nelsonic oh boy!!! **CANNOT WAIT** 

Is it the St. Pauls Maplin at 12? 👍 

I'll be looking into all the recommendations! 💯

**Comment by nelsonic** [comment]
I didn't _know_ that I would be working from client office today when I ordered it last week. 🤔  📆 
so I asked for delivery to Liverpool Street. (_see PDF I sent you_) store is close to "Skills Matter". 🎯 
Will try and be there for 12:00 ... hope you sleep well! 🛌

**Comment by sohilpandya** [comment]
![img_2469](https://cloud.githubusercontent.com/assets/2305591/22853396/33058314-f04d-11e6-94b3-7afac3f3b7cf.PNG)

Ordered another battery. Should be with us for Monday. ☺️

**Comment by iteles** [comment]
@nelsonic Shall we close this issue for now? We have the equipment, the next issue should be on how to use it most effectively 😊

**Comment by nelsonic** [comment]
Agreed. closing. 👍

**Comment by nelsonic** [comment]
This is why we can't have "nice things"...

https://www.bbc.co.uk/news/world-latin-america-45073385
![image](https://user-images.githubusercontent.com/194400/43684132-4f44ee5e-9892-11e8-8e5e-fff0328e05e4.png)

All it takes is **one _idiot_** to **spoil it** for **_all_ amateur aerial photographers**... 😞  

Also, not a very effective _military_ if they all _run_ at the _slightest_ sign of "danger"...
What happened to _protecting_ your "leaders"...?! 🙄 
Reminds me of the "Bodyguards" sketch in John Finnemore's Souvenir Programme:
https://www.comedy.co.uk/radio/finnemore_souvenir_programme/episodes/4/1/
... 
https://sites.google.com/view/playlistsnight/home
![john-finnemore-souvenir-program-playlist](https://user-images.githubusercontent.com/194400/43684950-dec380cc-98a1-11e8-85c8-b67916b03a27.png)
https://drive.google.com/file/d/1AxX7594pBYd9b23OH_ubZqY47y0Hxwjl/view
![jfsp-playlist](https://user-images.githubusercontent.com/194400/43684960-0255914c-98a2-11e8-923a-f402437b89f4.png)
Seriously tho, if you like _intellectual_ comedy, listen to it (download or stream). Thank me later. 😉
