### ISSUE TITLE
Packing and moving to Palmers Road

### ISSUE THREAD

**Issue by iteles** [dwyl/phase-two#35]
Now that we have made the decision to move #11 and bought the moving boxes #34, we need to make the move itself happen. 

## Overall checklist
+ [x] Pack MDC
  + [x] Garage (make space for boxes)
  + [x] Bedroom
  + [x] Office
  + [x] Bathroom
  + [x] Kitchen
  + [x] Living Room
  + [x] Upstairs storage cupboard
+ [x] Rent zipvan
+ [x] Move (load boxes at MDC, unload at Palmers Road
+ [x] Fix walls in office in MDC

**Comment by nelsonic** [comment]
![image](https://cloud.githubusercontent.com/assets/194400/20653984/9cf045f6-b50c-11e6-8c1d-7d62f352441f.png)
