### ISSUE TITLE
Braga?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#54]
_Last year_ an _opportunity_ arose to do a "_Phase Two_" project in Braga (Portugal).
and we decided to _consider_ the `<option>`... https://en.wikipedia.org/wiki/Braga
We wrote a (_basic_) "_back-of-the-envelope business plan_" 
and discussed it verbally (_at length_) over the Christmas break
and concluded that it was both financially and crucially _strategically_ worthwhile. 🌱  >> 🌳 
So we initiated the paperwork to secure an `<option>` for the project.
Ines made some notes on her phone but these were not transferred to GitHub at the time ... 😞 
It's been taking a `while` to sort out paperwork ... 
at this point it's still just an `<option>` and we are not yet "_committed_" to anything.
It's about to get "_serious_" so it's time to do a bit more planning and calculations.
Some time and cash is required but it will (_significantly_) _accelerate_ our progress towards the [goal](https://github.com/dwyl/phase-two/blob/master/phase-two-goal.md) 
for a _number_ of reasons.
Anyone interested in the _detail(s)_...?

**Comment by carolrmc** [comment]
yes please

**Comment by nelsonic** [comment]
Name idea: Creative Technology Rapid Learning Workspace (`CTRL+W`)

**Comment by nelsonic** [comment]
Research Screenshots:

## Local Amenities

There are great amenities within ***walking distance*** of **Braga House**.

### Supermarket (Pingo Douce)

Pingo Douce is a great little super market with very good fresh produce, they sell pretty much anything you would expect from a local supermarket including prepared foods and hygiene products.

[![Braga-House-to-Pingo-Douce](https://cloud.githubusercontent.com/assets/194400/25120415/e49a9780-2415-11e7-9474-ef866cacf7a6.png)](https://www.google.pt/maps/dir/41.5489875,-8.411476/41.5477188,-8.4145444/@41.5485149,-8.4138317,298m/data=!3m1!1e3!4m2!4m1!3e2)

[Google Map Link](https://www.google.pt/maps/dir/41.5489875,-8.411476/41.5477188,-8.4145444/@41.5485149,-8.4138317,298m/data=!3m1!1e3!4m2!4m1!3e2)

### 10 mins (750M) Walk to City Center (Avenida Central)

[![image](https://cloud.githubusercontent.com/assets/194400/25120839/807a76b0-2417-11e7-9521-6935699f51a9.png)](https://www.google.pt/maps/dir/41.5477469,-8.4143836/41.551884,-8.420075/@41.5496072,-8.4189221,595m/am=t/data=!3m1!1e3!4m2!4m1!3e2)

[Google Maps Directions](https://www.google.pt/maps/dir/41.5477469,-8.4143836/41.551884,-8.420075/@41.5496072,-8.4189221,595m/am=t/data=!3m1!1e3!4m2!4m1!3e2)

### Bus Station (Transport to All Major Cities, Airport and Geres)

All buses in the city cost €1.50 which is probably worth your time.

[![image](https://cloud.githubusercontent.com/assets/194400/25120627/cd08cf46-2416-11e7-827b-f85a406ac310.png)](https://www.google.pt/maps/dir/41.5477469,-8.4143836/Central+de+camionagem,+Braga,+Av.+Gen.+Norton+de+Matos+110,+4700-387+Braga/@41.5510823,-8.4239676,1182m/data=!3m1!1e3!4m8!4m7!1m0!1m5!1m1!1s0xd24fee947decd83:0x770d95b66932d3fc!2m2!1d-8.42517!2d41.555613)

[Google Maps Directions](https://www.google.pt/maps/dir/41.5477469,-8.4143836/Central+de+camionagem,+Braga,+Av.+Gen.+Norton+de+Matos+110,+4700-387+Braga/@41.5510823,-8.4239676,1182m/data=!3m1!1e3!4m8!4m7!1m0!1m5!1m1!1s0xd24fee947decd83:0x770d95b66932d3fc!2m2!1d-8.42517!2d41.555613)


### Football + Basketball Court



[![braga-6min-walk-to-basketball-football-court](https://cloud.githubusercontent.com/assets/194400/25118952/2f03524a-2410-11e7-9ab7-d92408357430.png)](https://www.google.pt/maps/dir/41.5466844,-8.4102835/41.5477188,-8.4145444/@41.5469662,-8.4131912,297m/data=!3m1!1e3!4m3!4m2!3e2!5i2)
[Google Map Link](https://www.google.pt/maps/dir/41.5466844,-8.4102835/41.5477188,-8.4145444/@41.5469662,-8.4131912,297m/data=!3m1!1e3!4m3!4m2!3e2!5i2)

## Nearby

### Beach @ Esposende 


A short bus/car journey from Braga, Esposende is an ***unspoiled beach*** with clean white sand, superb waves and gentle wind (_if you are into kite/wind surfing_)

![image](https://cloud.githubusercontent.com/assets/194400/25121256/028f6b5a-2419-11e7-95d6-972f2d0a4eed.png)

![citat-kite-esposende-web](https://cloud.githubusercontent.com/assets/194400/25121396/7c413776-2419-11e7-83f0-61d7f8bcc368.jpg)

[![braga-to-esposende](https://cloud.githubusercontent.com/assets/194400/25120954/e1ce09d6-2417-11e7-9c12-f04ae9476c62.png)](https://www.google.com/maps/dir/Braga/Esposende,+Portugal/@41.5173505,-8.7441275,11z/data=!4m14!4m13!1m5!1m1!1s0xd24febc6cf5d867:0xbc5d054162d1e218!2m2!1d-8.426507!2d41.5454486!1m5!1m1!1s0xd244bbaa150b227:0xa6078b869457d1d2!2m2!1d-8.7805652!2d41.5309169!3e0)

[Map Link](https://www.google.com/maps/dir/Braga/Esposende,+Portugal/@41.5173505,-8.7441275,11z/data=!4m14!4m13!1m5!1m1!1s0xd24febc6cf5d867:0xbc5d054162d1e218!2m2!1d-8.426507!2d41.5454486!1m5!1m1!1s0xd244bbaa150b227:0xa6078b869457d1d2!2m2!1d-8.7805652!2d41.5309169!3e0)

Read the Writeup in "Kite World" for Esposende: 
"_a flat water spot protected by the dunes in the river mouth that’s **perfect for beginners** and freestylers_"
http://www.kiteworldmag.com/travel/esposende-portugal/

### Gerês National Park

Within a short drive or €3.50 Bus Ride is the Geres Nature Reserve: https://en.wikipedia.org/wiki/Peneda-Ger%C3%AAs_National_Park

![geres-pontes-snow-capped](https://cloud.githubusercontent.com/assets/194400/25120305/66a7e940-2415-11e7-8121-6137b2a021af.jpg)

![geres-lakeside-deck-chairs](https://cloud.githubusercontent.com/assets/194400/25120210/16a22992-2415-11e7-90ae-bc465443217f.jpg)

![paddle-boarding-geres](https://cloud.githubusercontent.com/assets/194400/25120167/e62e50ec-2414-11e7-80bd-bdafdb16819f.jpg)


[![image](https://cloud.githubusercontent.com/assets/194400/25119514/6291de68-2412-11e7-96cd-60b81c969dd1.png)](https://www.google.pt/maps/dir/Braga/Caf%C3%A9+Da+Ponte,+Cemit%C3%A9rio+de+Rio+Caldo,+4845/@41.6534316,-8.4682081,11z/data=!4m14!4m13!1m5!1m1!1s0xd24febc6cf5d867:0xbc5d054162d1e218!2m2!1d-8.426507!2d41.5454486!1m5!1m1!1s0xd251efc582030ed:0x7aceda8540428f92!2m2!1d-8.1809879!2d41.6754544!3e0)
[Google Maps Link](https://www.google.pt/maps/dir/Braga/Caf%C3%A9+Da+Ponte,+Cemit%C3%A9rio+de+Rio+Caldo,+4845/@41.6534316,-8.4682081,11z/data=!4m14!4m13!1m5!1m1!1s0xd24febc6cf5d867:0xbc5d054162d1e218!2m2!1d-8.426507!2d41.5454486!1m5!1m1!1s0xd251efc582030ed:0x7aceda8540428f92!2m2!1d-8.1809879!2d41.6754544!3e0)

http://www.ikea.com/pt/pt/catalog/products/00102452/?query=MYDAL
![image](https://cloud.githubusercontent.com/assets/194400/25119395/e1462968-2411-11e7-8393-1983a2f5a221.png)

**Comment by nelsonic** [comment]
_Realistically_, Braga is _not_ a Tourist "_Destination_" ...
https://www.tripadvisor.com/Tourism-g189171-Braga_Braga_District_Northern_Portugal-Vacations.html

**Comment by nelsonic** [comment]
Cost of living in Braga: https://www.youtube.com/watch?v=tj3hwPqNfgY

**Comment by nelsonic** [comment]
### Recheio Cash & Carry (Wholesale for food, cleaning products and other consumables)
![image](https://cloud.githubusercontent.com/assets/194400/25135400/3236318c-244a-11e7-9c3c-d3694754a7b2.png)
[Google Map](https://www.google.pt/maps/dir/41.5477718,-8.4145331/Recheio+Cash+%26+Carry,+S.A.,+Rua+de+Vila+Nova+-+Nogueira,+Apartado+246,+4715-238+Braga/@41.5416056,-8.4274756,15z/am=t/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0xd24fecb29826aa5:0x2de888401327d00f!2m2!1d-8.42133!2d41.532055)

**Comment by nelsonic** [comment]
Santa Barabara Garden
![image](https://cloud.githubusercontent.com/assets/194400/25136352/abfb5acc-244c-11e7-9477-d965e6d4cfe5.png)
http://webraga.pt/visitar/parques/jardim-de-santa-barbara/
https://www.tripadvisor.com/Attraction_Review-g189171-d3873340-Reviews-The_Garden_of_Santa_Barbara-Braga_Braga_District_Northern_Portugal.html

![image](https://cloud.githubusercontent.com/assets/194400/25137153/d3d4d08a-244e-11e7-8109-52c74769cad4.png)
[Google Map](https://www.google.pt/maps/dir/31+de+Janeiro+(Seg+Social)/Garden+of+Santa+Barbara,+R.+da+Dr.+Justino+Cruz,+4700-317+Braga/@41.5498523,-8.4223168,17z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0xd24febec813a167:0x9bd681dbde5916d!2m2!1d-8.414384!2d41.547684!1m5!1m1!1s0xd24fee9d7767c47:0x5a7dd135cdb3f7ab!2m2!1d-8.4258723!2d41.55141!3e2)

**Comment by nelsonic** [comment]
A _smaller_ house on the same road but further from the city centre in _much_ worse state of repair is on the market for €595k
https://www.imovirtual.com/imoveis/casas/vende-se-moradia-31-de-janeiro-braga/6650556/
![image](https://cloud.githubusercontent.com/assets/194400/25578248/9ec946b2-2e64-11e7-95dc-c012f22624f0.png)

If we simply refurbish the house, get it working as a Hostel and sell it on we will make an "_adequate_" return. But that would be a _short-term-goal_, which is not the purpose of "Phase Two"!! 🚀

**Comment by nelsonic** [comment]
Property Search Result page: https://www.imovirtual.com/imoveis/casas/venda/-/Braga/size_from,5,list_mode,3,sort,2,search_page,61

**Comment by nelsonic** [comment]
`T1h` _may_ have been a bit optimistic ... 😜

**Comment by nelsonic** [comment]
`Braga House` is _solving_ `this` problem:
![image](https://cloud.githubusercontent.com/assets/194400/25699028/5a8d8326-30b9-11e7-9854-41d39581d83f.png)
Could not have expressed it better.

**Comment by nelsonic** [comment]
`Braga House` is _solving_ `this` problem:
![image](https://cloud.githubusercontent.com/assets/194400/25699028/5a8d8326-30b9-11e7-9854-41d39581d83f.png)
![image](https://cloud.githubusercontent.com/assets/194400/25699069/89c58daa-30b9-11e7-8168-04b80fa9545a.png)
Thanks for _articulating_ it Bradley. 👍

**Comment by nelsonic** [comment]
Having comfortable chairs (_and standing desks_) _matters_:
![image](https://cloud.githubusercontent.com/assets/194400/25720499/08377f40-3105-11e7-97a9-b852a6dde41f.png)

**Comment by nelsonic** [comment]
The house on the same street is apparently _still_ for sale: 
https://www.imovirtual.com/anuncio/vende-se-moradia-31-de-janeiro-braga-IDrU72.html
![image](https://user-images.githubusercontent.com/194400/35474722-1c536040-038a-11e8-99e7-5b2ea402eac4.png)
@iteles should we ask to go and see it?

**Comment by iteles** [comment]
Definitely! Can you call in case they're still open?

**Comment by nelsonic** [comment]
I called. got voicemail. obvs they are closed at 17:45 on a Saturday.
I left a message asking if we could see it. 👍

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/home 😉
