### ISSUE TITLE
(Can we have a Pet) Parrot?! 😮 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#73]
I've _always_ wanted to have a Pet Parrot. ❤️ 

![pet-parrot](https://user-images.githubusercontent.com/194400/45941521-74e6f600-bfd6-11e8-90c5-cd8293fc6031.png)
https://aeon.co/essays/why-does-keeping-a-bird-in-a-cage-make-people-happy

The question is: is it _fair_ to remove a bird from the wild just so we (humans) can have an animal companion that "talks"?

**Comment by carolrmc** [comment]
I think that has been a moral dilemma for thinking people through the
centuries!  Was it fair to domesticate any animal in that case?  I don’t
know where the fine line is between it being morally acceptable and not. I
have this dilemma about the cat - she should be an out door cat, that’s her
inheritance, but could she survive traffic, dogs, other cats now?

**Comment by carolrmc** [comment]
I would be careful of having birds in a place you are welcoming paying
guests. Many people have feather fobias - they hate moving wings, or
feathers or birds in general just give them the creeps!

**Comment by nelsonic** [comment]
@carolrmc yes, thanks for _reminding_ us that some people are ***Ornithophobic*** ... 🙄 

But let's _think_ about this for a second ... are we going to:
**a)** cater to _all_ the Phobias https://en.wikipedia.org/wiki/List_of_phobias and avoid living our lives 😞 
***or***
**b)** build an **_awesome_ bird-_friendly_ garden** with _many_ feeders, nesting boxes and water sources
so that the ***Ornothologists*** can enjoy the space and bird-curious people can discover/learn. 🎉 

Yes, we should be "_sensitive_" to people's fears, (_however irrational they may be!_)
but if we were catering to _Agoraphobic_ or _Aquaphobic_ people 
we would have _no_ windows and no fish pond either! 😕 

I'm not saying we _must_ have _tropical_ birds. 🐦 
But I am ***100%*** going to _encourage_ local birds to nest in the garden 🌳 
because I find birdsong to be one of the most relaxing sounds in the world. 🎶 😍

**Comment by nelsonic** [comment]
@carolrmc it's like you're "reading our mind"... 😉 
We are going to have built-in/hidden speakers in the learning room which will be used for both multimedia e.g: Video Conferences or Watching Online Lectures
***and*** piping in calming music (_all controlled within the "home app"_) 

As for "can’t keep a cat" I _respectfully_ refute that claim; all feeders/nests will be high enough and without cat accessible "ladders" to allow birds to nest/feed without risk of a domestic cat "catching" them. 

This will require additional _research_ and _design_ to ensure we get the correct height. **`help wanted`**!

**Comment by carolrmc** [comment]
How will you keep away the pesky pigeons?

**Comment by nelsonic** [comment]
There aren't a lot of pigeons in Braga. (_thankfully_)
But also, there isn't a _reason_ to keep them away unless they are _genuinely_ being a _pest_!

(_if pigeons become a nuisance, we have still have a couple of BB Guns with [Bio-Degradeable Pellets](https://bbguns4less.co.uk/biodegradable-0-20g-bb-pellets/) ... from when we had a Roof Garden in London, they don't injure/kill the birds, simply scare them off..._)

**Comment by carolrmc** [comment]
Pigeons tend to chase other birds away, and B.B. guns scare all birds
indiscriminately, they don’t target only pigeons!

**Comment by nelsonic** [comment]
@carolrmc are you suggesting that I don't have "good aim"...? 
You _appear_ to be forgetting how much I practiced in my youth ...
I can hit a fly in _motion_ from 2m or a 50cent coin from 10m. 
Pigeons were _not_ a problem in our LDN Roof Garden, _trust me_. 
Please avoid being "_pre-occupied_" by something that _won't_ be any cause for concern.
_Focus_ on the subject/topic of the issue: Parrots!!
